version: '3'

services:
  mariadb:
    build:
      context: .
      dockerfile: .mariadbdocker/Dockerfile
    image: sing_along_mariadb
    ports:
      # note that forward to port 3307!
      - 3307:3306
    environment:
      MYSQL_DATABASE: sing_along
      MYSQL_USER: sing_along_usr
      MYSQL_PASSWORD: J7Gu7lLAyXMTp3AH
      MYSQL_ROOT_PASSWORD: TecNNLrw5AH335g0

